touchscreen: lge_sub: remove unused variable hide_lockscreen_coord
../../../../../../kernel/lge/sm7250/drivers/input/touchscreen/lge_sub/touch_sub_core.c:109:7: error: unused variable 'hide_lockscreen_coord' [-Werror,-Wunused-variable]
  109 |         bool hide_lockscreen_coord =
      |              ^~~~~~~~~~~~~~~~~~~~~

Change-Id: I95adaa95f22c77ba26ca2f5dde2f40b0f0ec67f4
Signed-off-by: Han Sol Jin <hansol@hansol.ca>